# http://localhost:9897/fx67llpr
server:
  # 设置项目启动的端口号
  port: 9897
  # 设置项目访问路径（上下文路径）
  servlet:
    context-path: /fx67llpr
  # spring基本配置
  spring:
    # 数据库配置
    #    datasource:
    #      driver-class-name: com.mysql.jdbc.Driver
    #      password: xxx
    #      username: xxx
    #      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&charcterEncoding=UTF-8
    resources:
      # 多个目录使用逗号隔开，现在可以访问的目录有
      # http://localhost:9897/fx67llpr/public
      # http://localhost:9897/fx67llpr/static
      # http://localhost:9897/fx67llpr/fx67ll
      static-locations: classpath:/public/,classpath:/static/,classpath:/fx67ll/

# 日志输出配置
# logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} {%thread} %logger- %msg%n"
#    level: debug
#  file:
#    path: "."
#    name: "springboot.log"


# 相比于application.porperties文件的区别
# 不能使用tab键，必须使用空格键
# 驼峰规则用-代替，例如：userName = user-name